#!/usr/bin/env bash

source "$(dirname "$0")/globals"

main() {
    if [[ -d "$INSTALL_DIR" ]]; then
        rm "$INSTALL_DIR/$SCRIPT_NAME"
    fi
    if [[ -d "$MAN_DIR" ]]; then
        rm "$MAN_DIR/$MAN_NAME"
    fi
}

main
